In [12]:
import numpy as np

In [13]:
a = 3
b = 2
x = np.array([2, 3, 1, 0])
y = np.array([5, 1, 5, 0])

#print out the vector operation results

In [14]:
np.add(x,a)

array([5, 6, 4, 3])

In [15]:
np.dot(b, x)

array([4, 6, 2, 0])

In [16]:
np.add(x, y)

array([7, 4, 6, 0])

In [17]:
np.dot(x, y)

18

##The matrices

In [22]:
A = np.array([1,2,3,4]).reshape(2, 2)
I = np.array([1,0,0,1]).reshape(2, 2)

In [23]:
A

array([[1, 2],
       [3, 4]])

In [24]:
I

array([[1, 0],
       [0, 1]])

In [25]:
np.dot(A, I)

array([[1, 2],
       [3, 4]])

In [26]:
##Determinant

In [27]:
np.linalg.det(A)

-2.0000000000000004